<!DOCTYPE sql-queries [
<!ELEMENT sql-queries (sql-query)*>
<!ELEMENT sql-query (#PCDATA)>
<!ATTLIST sql-query id CDATA #REQUIRED>
]>
<sql-queries>
<sql-query id="register">
       <![CDATA[insert into user_tbl (username,art_form,email,mobile,country,address,city,zipcode,date,profile_pic)
                values (?,?,?,?,?,?,?,?,?,?)]]>
   </sql-query>
<sql-query id="eventRegister">
       <![CDATA[insert into dec_event_tbl (name,teacher_name,teacher_mobile,teacher_email,art_category,art_form,
                                      participation,gender,age,comp_category,identity_card_type,identity_card_number,email,
                                      mobile,address,city,zipcode,date,profile_pic,country,amount,comp_level)
                values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]]>
   </sql-query>


 <sql-query id="getProfiles">
       <![CDATA[select * from user_tbl]]>
   </sql-query>

    <sql-query id="getRegistrationProfiles">
       <![CDATA[select * from dec_event_tbl where video_link is not null]]>
   </sql-query>

   
  <sql-query id="getMember">
       <![CDATA[select * from user_tbl where id =?  ]]>
   </sql-query>

    <sql-query id="insertMarks">
       <![CDATA[insert into dec_event_marks (participant_id,judge_id,marks)
                values (?,?,?)]]>
    </sql-query>

        <sql-query id="updateMarks">
       <![CDATA[update dec_event_marks set marks = ? where participant_id = ? and judge_id = ?]]>
    </sql-query>

     <sql-query id="getJudgesList">
       <![CDATA[select * from judges  ]]>
   </sql-query>


</sql-queries>